[unix_http_server]
file=/project/blog/supervisor.sock
chmod=0700  

[inet_http_server]
port = 0.0.0.0:9001    ; 绑定到本地回环
username = admin         ; 网页用户名
password = Zdjsrztx2@   ; 网页密码

[supervisord]
logfile=/project/blog/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/project/blog/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///project/blog/supervisor.sock


[program:blog]
command=uv run main.py
directory=/project/blog/back
user=root
autostart=true
autorestart=true
startsecs=10
startretries=3
stderr_logfile=/project/blog/back/blog.err.log
stdout_logfile=/project/blog/back/blog.out.log
environment=PYTHONPATH="/project/blog/back",ENV="production"